// Generated by Wrangler by running `wrangler types`

interface Env {
	SEARCH_CACHE: KVNamespace;
	ENVIRONMENT: "development" | "production" | "staging";
	PRIMARY_INDEX_DO: DurableObjectNamespace /* SearchIndexDO */;
	REGION_REPLICA_DO: DurableObjectNamespace /* SearchIndexDO */;
	LOCAL_REPLICA_DO: DurableObjectNamespace /* SearchIndexDO */;
	COLD_STORAGE_DO: DurableObjectNamespace /* SearchIndexDO */;
	INDEX_QUEUE: Queue;
}
